# Hashicorp secret store manifest
- kind: HashicorpKeys
  version: 0.0.1
  name: keystore
  specs:
    mountPoint: quorum
    address: http://vault:8200
    tokenPath: /vault/token/.root
    namespace: demo